
package VistaGestorEmpleados;
import GestionEmpleados.Area;
import GestionEmpleados.Empleado;
import GestionEmpleados.Enum.TipoContrato;
import GestionEmpleados.GestorEmpleados;
import GestionEmpleados.RegistroPago;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jokan5443
 */
public class AdminReportes1 extends javax.swing.JPanel {
    
    GestorEmpleados gestor;  
    
    public AdminReportes1(GestorEmpleados gestor) {
        
        initComponents();
        
        this.gestor = gestor;
        
        List<RegistroPago> pagos = gestor.getMisRagistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusquedaContrato = new javax.swing.JPanel();
        btnBuscarInformacion = new javax.swing.JButton();
        lblBuscarOpc2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BoxSeleccion = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaReportes = new javax.swing.JTable();

        setBackground(new java.awt.Color(17, 50, 77));

        panelBusquedaContrato.setBackground(new java.awt.Color(0, 0, 0));
        panelBusquedaContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnBuscarInformacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscarInformacion.setText("Buscar Información");
        btnBuscarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInformacionActionPerformed(evt);
            }
        });

        lblBuscarOpc2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblBuscarOpc2.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarOpc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc2.setText("Revisar Reportes");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Seleccione :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escritura.png"))); // NOI18N
        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BoxSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Empleados", "Pagos", "Áreas", "Contratos", "Nominas", "Incidencias", "Jerarquia" }));

        javax.swing.GroupLayout panelBusquedaContratoLayout = new javax.swing.GroupLayout(panelBusquedaContrato);
        panelBusquedaContrato.setLayout(panelBusquedaContratoLayout);
        panelBusquedaContratoLayout.setHorizontalGroup(
            panelBusquedaContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaContratoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panelBusquedaContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBuscarOpc2))
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(112, 112, 112))
        );
        panelBusquedaContratoLayout.setVerticalGroup(
            panelBusquedaContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaContratoLayout.createSequentialGroup()
                .addGroup(panelBusquedaContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(panelBusquedaContratoLayout.createSequentialGroup()
                        .addComponent(lblBuscarOpc2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBusquedaContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información:"));

        TablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(TablaReportes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusquedaContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelBusquedaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private DefaultTableModel modeloTabla;
    
    private String buscarNombreAreaDeEmpleado(Empleado emp){
    for(Area area : gestor.getMisAreas()){
     if(area.getListaEmpleadoIds().contains(emp))
     return area.getNombre();
    }    
    return "No asignado";
    }
    
    private void mostrarEmpleadosEnTabla(){
        modeloTabla.setColumnIdentifiers(new Object[]{
        "ID", "Nombre", "Apelllido", "Tipo Contrato", "Cargo", "Area"
        });
     
       for(Empleado emp : gestor.getMisEmpleados()){ 
          String area = buscarNombreAreaDeEmpleado(emp);
          modeloTabla.addRow(new Object[] {
          emp.getId(),
          emp.getNombre(),
          emp.getApellido(),
          emp.getTipoContrato(),
          emp.getAreaLabor()
          });
    }
       
    TablaReportes.setModel(modeloTabla);
       
    }
    
    private void mostrarAreasEnTabla(){
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnIdentifiers(new String[]
    {"ID Área", "Nombre Área"});
    
    for (Area area : gestor.getMisAreas()){
    modeloTabla.addRow(new Object[]
    {area.getIdArea(), area.getNombre()});
    }
    }
    
    private void mostrarPagosEnTabla(){
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnIdentifiers(new String[]
    {"ID Registro", "ID Empleado", "Monto", "Fecha"});
    
    for(RegistroPago Pago : gestor.getMisRagistro()){
    modeloTabla.addRow(new Object[]{
    // como todavia no esta los pagos es un ejemplo de como deberia ser
    pago.getIdRegistro(),
    pago.getEmpleado().getIdEmpleado(),
    pago.getMonto(),
    pago.getFecha()
    });
    }
    }
    
    private void mostrarContratosEnTabla(){
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnIdentifiers(new String[]
    {"ID Empleado","Tipo Contrato", "Fecha Inicio", "Fecha Fin"}); //Fecha Renovacion
    
    for(Empleado e : gestor.getMisEmpleados()){
    TipoContrato c = e.getTipoContrato();
    modeloTabla.addRow(new Object[]{
    e.getId(),
    //aqui tambien como no estan los contratos ps tdvia no puedo avanzar
    // es un ejemplo de como deberia ser
    c != null ? c.getTipo() : "Sin contrato",
    c != null ? c.getFechaInicio() : "",
    c != null ? c.getFechaFin() : ""
    });
    }
    }
    
    private void mostrarNominasEnTabla(){
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnIdentifiers(new String[]
    { "ID Empleado", "Nombre","Sueldo Base",
      "Bonificciones","Descuentos","SueldoTotal"
    });
    
    for(Empleado e : gestor.getMisEmpleados()){
    AdminNominas n =e.getNomina();
    modeloTabla.addRow(new Object[]{
    e.getId(),
    e.getNombre(),
    n.getSueldoBase(),
    n.getBonificaciones(),
    n.getDescuentos(),
    n.getSueldoNeto()
    });
    }   
    }
    
    private void mostrarIncidenciasEnTabla(){
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnIdentifiers(new String[]
    {"ID Empleado","Nombre","Tipo Incidencia","Fecha", "Descripcion"});
    
    for(Empleado e : gestor.getMisEmpleados())
     for(AdminIncidencias i : e.getIncidencias()){
     modeloTabla.addRow(new Object[]{
     e.getId(),
     e.getNombre(),
     i.getTipo(),
     i.getFecha(),
     i.getDescripcion()
     });
     }
    }
    
    private void mostrarJerarquiaEnTabla(){
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInformacionActionPerformed
    String seleccion = BoxSeleccion.getSelectedItem().toString();
    
    switch (seleccion){
        case "Empleados":
        mostrarEmpleadosEnTabla();
        break;
        case "Áreas":
        mostrarAreasEnTabla();
        break;
        case "Pagos":
        mostrarPagosEnTabla();  
        break;
        case "Contratos":
        mostrarContratosEnTabla();
        break;
        case "Nominas":
        mostrarNominasEnTabla();
        break;
        case "Incidencias":
        mostrarIncidenciasEnTabla();
        break;
        case "Jerarquia":
        mostrarJerarquiaEnTabla();
        break;
        default:
      JOptionPane.showMessageDialog(this ,"Seleccione una opcion valida.");      
    }   
    }//GEN-LAST:event_btnBuscarInformacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxSeleccion;
    private javax.swing.JTable TablaReportes;
    private javax.swing.JButton btnBuscarInformacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBuscarOpc2;
    private javax.swing.JPanel panelBusquedaContrato;
    // End of variables declaration//GEN-END:variables
}
