package VistaGestorEmpleados;

import GestionEmpleados.Empleado;
import GestionEmpleados.*;
import GestionEmpleados.Enum.TipoContrato;
import javax.swing.JOptionPane;


public class AdminEmpleados2 extends javax.swing.JPanel {

    GestorEmpleados gestor;
    
    public AdminEmpleados2(GestorEmpleados gestor) {
        initComponents();
        this.setSize(840, 600);
        
        this.gestor = gestor;
        
        TxtBusNom.setEditable(false);
        TxtBusApp.setEditable(false);
        TxtBusCorreo.setEditable(false);
        TxtBusDNI.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDespedir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxtBusNom = new javax.swing.JTextField();
        TxtBusApp = new javax.swing.JTextField();
        TxtBusDNI = new javax.swing.JTextField();
        TxtBusCorreo = new javax.swing.JTextField();
        TxtBusID = new javax.swing.JTextField();
        btnMostrarAsis = new javax.swing.JButton();
        btnDespedir = new javax.swing.JButton();
        PanelModificar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtModID = new javax.swing.JTextField();
        TxtModNom = new javax.swing.JTextField();
        TxtModApp = new javax.swing.JTextField();
        TxtModDNI = new javax.swing.JTextField();
        TxtModCorreo = new javax.swing.JTextField();
        CboxModCont = new javax.swing.JComboBox<>();
        CboxModCargo = new javax.swing.JComboBox<>();
        CboxModArea = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnMod = new javax.swing.JButton();
        PanelBusqueda = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jsEmpleados = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jtBuscar = new javax.swing.JTabbedPane();
        panelIdBuscar = new javax.swing.JPanel();
        lblIDBuscar = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        panelAreaBuscar = new javax.swing.JPanel();
        lbIdAreaBuscar = new javax.swing.JLabel();
        txtIdAreaBuscar = new javax.swing.JTextField();
        panelEstadoLaboralBuscar = new javax.swing.JPanel();
        lblEstadoBuscar = new javax.swing.JLabel();
        listaEstadoBuscar = new javax.swing.JComboBox<>();
        lblBuscarOpc = new javax.swing.JLabel();
        PanelModificar1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtEmpID = new javax.swing.JTextField();
        TxtEmpNom = new javax.swing.JTextField();
        TxtEmpApp = new javax.swing.JTextField();
        TxtEmpDNI = new javax.swing.JTextField();
        TxtEmpCorreo = new javax.swing.JTextField();
        CboxContr = new javax.swing.JComboBox<>();
        CboxCargo = new javax.swing.JComboBox<>();
        CboxArea = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        BntRegistrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 50, 77));

        PanelDespedir.setBorder(javax.swing.BorderFactory.createTitledBorder("DespedirEmpleado"));

        jLabel16.setText("ID Empleado:");

        jLabel18.setText("Nombre:");

        jLabel19.setText("Apellido:");

        jLabel20.setText("DNI:");

        jLabel21.setText("Correo:");

        btnMostrarAsis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarAsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-del-portapapeles.png"))); // NOI18N
        btnMostrarAsis.setText("Mostrar Datos");
        btnMostrarAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAsisActionPerformed(evt);
            }
        });

        btnDespedir.setText("Despedir");
        btnDespedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDespedirLayout = new javax.swing.GroupLayout(PanelDespedir);
        PanelDespedir.setLayout(PanelDespedirLayout);
        PanelDespedirLayout.setHorizontalGroup(
            PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDespedirLayout.createSequentialGroup()
                .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDespedirLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(10, 10, 10)
                        .addComponent(TxtBusApp))
                    .addGroup(PanelDespedirLayout.createSequentialGroup()
                        .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(20, 20, 20)
                        .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBusCorreo)
                            .addComponent(TxtBusDNI)))
                    .addGroup(PanelDespedirLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBusNom))
                    .addGroup(PanelDespedirLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBusID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDespedirLayout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarAsis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDespedir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        PanelDespedirLayout.setVerticalGroup(
            PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDespedirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarAsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TxtBusNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TxtBusApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TxtBusDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDespedirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TxtBusCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnDespedir)
                .addContainerGap())
        );

        PanelModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("ModificarEmpleado"));

        jLabel1.setText("ID Empleado:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel5.setText("DNI:");

        jLabel6.setText("Correo:");

        CboxModCont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISCAPACIDAD", "TEMPORAL", "RENOVABLE", "INDEFINIDO", "DESPEDIDO" }));

        CboxModCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERARIO", "SUPERVIDOR", "JEFE" }));

        jLabel13.setText("Tipo Contrato:");

        jLabel14.setText("Cargo:");

        jLabel15.setText("Área:");

        BtnMod.setText("Buscar");
        BtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModificarLayout = new javax.swing.GroupLayout(PanelModificar);
        PanelModificar.setLayout(PanelModificarLayout);
        PanelModificarLayout.setHorizontalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtModID))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(TxtModNom))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(TxtModApp))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67)
                        .addComponent(TxtModDNI))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnMod))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtModCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(12, 12, 12)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CboxModCont, 0, 160, Short.MAX_VALUE)
                                .addComponent(CboxModCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CboxModArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelModificarLayout.setVerticalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtModID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtModNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtModApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtModDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtModCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxModCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxModCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxModArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addComponent(BtnMod)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        PanelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        PanelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("PanelBusqueda"));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        jsEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Empleados"));
        jsEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsEmpleados.setViewportView(tbLista);

        jtBuscar.setToolTipText("");

        lblIDBuscar.setText("Id Empleado:");

        javax.swing.GroupLayout panelIdBuscarLayout = new javax.swing.GroupLayout(panelIdBuscar);
        panelIdBuscar.setLayout(panelIdBuscarLayout);
        panelIdBuscarLayout.setHorizontalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIDBuscar)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(171, 171, 171))
        );
        panelIdBuscarLayout.setVerticalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblIDBuscar))
        );

        jtBuscar.addTab("ID", panelIdBuscar);

        lbIdAreaBuscar.setText("Id Area: ");

        javax.swing.GroupLayout panelAreaBuscarLayout = new javax.swing.GroupLayout(panelAreaBuscar);
        panelAreaBuscar.setLayout(panelAreaBuscarLayout);
        panelAreaBuscarLayout.setHorizontalGroup(
            panelAreaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaBuscarLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(lbIdAreaBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdAreaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(166, 166, 166))
        );
        panelAreaBuscarLayout.setVerticalGroup(
            panelAreaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdAreaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbIdAreaBuscar))
        );

        jtBuscar.addTab("Area", panelAreaBuscar);

        lblEstadoBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoBuscar.setText("Estado laboral:");

        listaEstadoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "DESPEDIDO" }));

        javax.swing.GroupLayout panelEstadoLaboralBuscarLayout = new javax.swing.GroupLayout(panelEstadoLaboralBuscar);
        panelEstadoLaboralBuscar.setLayout(panelEstadoLaboralBuscarLayout);
        panelEstadoLaboralBuscarLayout.setHorizontalGroup(
            panelEstadoLaboralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLaboralBuscarLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblEstadoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelEstadoLaboralBuscarLayout.setVerticalGroup(
            panelEstadoLaboralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLaboralBuscarLayout.createSequentialGroup()
                .addGroup(panelEstadoLaboralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoBuscar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtBuscar.addTab("Estado", panelEstadoLaboralBuscar);

        lblBuscarOpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc.setText("Buscar por(en blanco para todos):");

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsEmpleados)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                                .addComponent(lblBuscarOpc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblBuscarOpc)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelModificar1.setBorder(javax.swing.BorderFactory.createTitledBorder("ModificarEmpleado"));

        jLabel7.setText("ID Empleado:");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Apellido:");

        jLabel10.setText("DNI:");

        jLabel11.setText("Correo:");

        CboxContr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISCAPACIDAD", "TEMPORAL", "RENOVABLE", "INDEFINIDO", "DESPEDIDO" }));

        CboxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERARIO", "SUPERVIDOR", "JEFE" }));

        jLabel30.setText("Tipo Contrato:");

        jLabel31.setText("Cargo:");

        jLabel32.setText("Área:");

        BntRegistrar.setText("Registrar");
        BntRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModificar1Layout = new javax.swing.GroupLayout(PanelModificar1);
        PanelModificar1.setLayout(PanelModificar1Layout);
        PanelModificar1Layout.setHorizontalGroup(
            PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificar1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TxtEmpID))
                    .addGroup(PanelModificar1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(44, 44, 44)
                        .addComponent(TxtEmpNom))
                    .addGroup(PanelModificar1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42)
                        .addComponent(TxtEmpApp))
                    .addGroup(PanelModificar1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(67, 67, 67)
                        .addComponent(TxtEmpDNI))
                    .addGroup(PanelModificar1Layout.createSequentialGroup()
                        .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(12, 12, 12)
                        .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CboxContr, 0, 160, Short.MAX_VALUE)
                                .addComponent(CboxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CboxArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificar1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BntRegistrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificar1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtEmpCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelModificar1Layout.setVerticalGroup(
            PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtEmpNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmpApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmpDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmpCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(28, 28, 28)
                .addComponent(BntRegistrar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelDespedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDespedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        TxtEmpID.setText("");
        TxtEmpNom.setText("");
        TxtEmpApp.setText("");
        TxtEmpDNI.setText("");
        TxtEmpCorreo.setText("");
        CboxContr.setSelectedIndex(0);
        CboxArea.setSelectedIndex(0);
        CboxCargo.setSelectedIndex(0);
        
        TxtModID.setText("");
        TxtModNom.setText("");
        TxtModApp.setText("");
        TxtModDNI.setText("");
        TxtModCorreo.setText("");
        CboxModCont.setSelectedIndex(0);
        CboxModArea.setSelectedIndex(0);
        CboxModCargo.setSelectedIndex(0);
    }  
    
    private void btnMostrarAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAsisActionPerformed
        
        try {
            int id = Integer.parseInt(TxtBusID.getText());
            Empleado emp = gestor.getEmpleado(id);
            if (emp != null) {
                TxtBusID.setText(String.valueOf(emp.getId()));
                TxtBusNom.setText(emp.getNombre());
                TxtBusApp.setText(emp.getApellido());
                TxtBusDNI.setText(emp.getDni());
                TxtBusCorreo.setText(emp.getEmail());
            } else {
                JOptionPane.showMessageDialog(this, "Error... No existe el empleado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error... Número inválido.");
        }
        
    }//GEN-LAST:event_btnMostrarAsisActionPerformed

    private void BntRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntRegistrarActionPerformed
        try {
            int id = Integer.parseInt(TxtEmpID.getText().trim());
            Empleado emp = gestor.getEmpleado(id);
            
            if (emp == null){
                
                String Nombre = TxtEmpNom.getText().trim();
                String Apellido = TxtEmpApp.getText().trim();
                String DNI = TxtEmpDNI.getText().trim();
                String Correo = TxtEmpCorreo.getText().trim();
                String TipoContratoEmp = CboxContr.getSelectedItem().toString();
                String CargoEmp = CboxCargo.getSelectedItem().toString();
                String AreaEmp = CboxArea.getSelectedItem().toString();
                
                if(TxtEmpID.getText().trim().isEmpty() ||
                        Nombre.isEmpty() ||
                        Apellido.isEmpty()|| 
                        DNI.isEmpty() ||
                        Correo.isEmpty() ||
                        TipoContratoEmp.equals("Seleccionar") ||
                        CargoEmp.equals("Seleccionar") ||
                        AreaEmp.equals("Seleccionar")
                    )
                {
                    JOptionPane.showMessageDialog(this, "Completa todos los campos porfavor :)");
                    return;
                }     
                
                int idArea = 0;
                    
                for(Area area: gestor.getMisAreas()){
                    if(AreaEmp.equals(area.getNombre()))
                        idArea = area.getIdArea();
                }
                
                TipoContrato tipoCont = null;
                
                switch (TipoContratoEmp){
                    case "DISCAPACIDAD": tipoCont = TipoContrato.DISCAPACIDAD; 
                        break;
                    case "TEMPORAL": tipoCont = TipoContrato.TEMPORAL; 
                        break;
                    case "RENOVABLE": tipoCont = TipoContrato.RENOVABLE; 
                        break;
                    case "INDEFINIDO": tipoCont = TipoContrato.INDEFINIDO; 
                        break;
                    case "DESPEDIDO": tipoCont = TipoContrato.DESPEDIDO; 
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Tipo de contrato no válido.");
                        return;
                }
                
                if(CargoEmp.equals("OPERARIO")){
                    Operario operario = new Operario(idArea, 5, gestor.getMisEmpleados().size(), Nombre,
                        Apellido, Correo, DNI, null, null, tipoCont, 0);
                    
                    gestor.addEmpleado(operario);
                } else if (CargoEmp.equals("SUPERVIDOR")){
                    Supervisor supervisor = new Supervisor(idArea, 7.5, gestor.getMisEmpleados().size(), Nombre,
                        Apellido, Correo, DNI, null, null, tipoCont, 0);
                    
                    gestor.addEmpleado(supervisor);
                } else {
                    Jefe jefe = new Jefe(idArea, 10, gestor.getMisEmpleados().size(), Nombre,
                        Apellido, Correo, DNI, null, null, tipoCont);
                    
                    gestor.addEmpleado(jefe);
                }
                
                
                limpiarCampos();
            }else {
                JOptionPane.showMessageDialog(this, "Error... No se puede ingresar un empleado ya existente.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error... Número inválido.");
        }
        
    }//GEN-LAST:event_BntRegistrarActionPerformed

    private void btnDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespedirActionPerformed

        String IdTexto =TxtBusID.getText();
            if(IdTexto.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese una ID.");
            return;
        }
        
        if(gestor.getMisEmpleados().isEmpty()){
            JOptionPane.showMessageDialog(this,"No hay empleados registrados.");
            return;
        }
        
        int idBuscado;

        try{
            idBuscado = Integer.parseInt(IdTexto);
        }                                                    
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"El ID debe ser un numero.");
            return;
        }
        
        Empleado emp = gestor.getEmpleado(idBuscado);
        
        if(emp != null){
            
            int confirm = JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de eliminar al empleado con ID " + idBuscado + "?", 
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                gestor.dropEmpleado(emp);
                JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
            } else{
                limpiarCampos();
                return;
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Error... El empleado no existe.");
        }
        
    }//GEN-LAST:event_btnDespedirActionPerformed

    private void BtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModActionPerformed

        if (BtnMod.getText().equals("Buscar")) {
            try {
                int id = Integer.parseInt(TxtModID.getText());
                Empleado emp = gestor.getEmpleado(id);
                if (emp != null) {
                    TxtBusID.setText(String.valueOf(emp.getId()));
                    TxtBusNom.setText(emp.getNombre());
                    TxtBusApp.setText(emp.getApellido());
                    TxtBusDNI.setText(emp.getDni());
                    TxtBusCorreo.setText(emp.getEmail());
                  
                    TxtModID.setEditable(false);
                    BtnMod.setText("Modificar");
                } else {
                    JOptionPane.showMessageDialog(this, "Error... No existe el empleado.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error... Número inválido.");
            }
        } else {
            int id = Integer.parseInt(TxtBusID.getText());
            String Nombre = TxtModNom.getText().trim();
            String Apellido = TxtModApp.getText().trim();
            String DNI = TxtModDNI.getText().trim();
            String Correo = TxtModCorreo.getText().trim();
            String TipoContratoEmp = CboxModCont.getSelectedItem().toString();
            String CargoEmp = CboxModCargo.getSelectedItem().toString();
            String AreaEmp = CboxModArea.getSelectedItem().toString();
            
            
            
            limpiarCampos();
            TxtModID.setEditable(true);
            BtnMod.setText("Buscar");
        }
    }//GEN-LAST:event_BtnModActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntRegistrar;
    private javax.swing.JButton BtnMod;
    private javax.swing.JComboBox<String> CboxArea;
    private javax.swing.JComboBox<String> CboxCargo;
    private javax.swing.JComboBox<String> CboxContr;
    private javax.swing.JComboBox<String> CboxModArea;
    private javax.swing.JComboBox<String> CboxModCargo;
    private javax.swing.JComboBox<String> CboxModCont;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JPanel PanelDespedir;
    private javax.swing.JPanel PanelModificar;
    private javax.swing.JPanel PanelModificar1;
    private javax.swing.JTextField TxtBusApp;
    private javax.swing.JTextField TxtBusCorreo;
    private javax.swing.JTextField TxtBusDNI;
    private javax.swing.JTextField TxtBusID;
    private javax.swing.JTextField TxtBusNom;
    private javax.swing.JTextField TxtEmpApp;
    private javax.swing.JTextField TxtEmpCorreo;
    private javax.swing.JTextField TxtEmpDNI;
    private javax.swing.JTextField TxtEmpID;
    private javax.swing.JTextField TxtEmpNom;
    private javax.swing.JTextField TxtModApp;
    private javax.swing.JTextField TxtModCorreo;
    private javax.swing.JTextField TxtModDNI;
    private javax.swing.JTextField TxtModID;
    private javax.swing.JTextField TxtModNom;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDespedir;
    private javax.swing.JButton btnMostrarAsis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jsEmpleados;
    private javax.swing.JTabbedPane jtBuscar;
    private javax.swing.JLabel lbIdAreaBuscar;
    private javax.swing.JLabel lblBuscarOpc;
    private javax.swing.JLabel lblEstadoBuscar;
    private javax.swing.JLabel lblIDBuscar;
    private javax.swing.JComboBox<String> listaEstadoBuscar;
    private javax.swing.JPanel panelAreaBuscar;
    private javax.swing.JPanel panelEstadoLaboralBuscar;
    private javax.swing.JPanel panelIdBuscar;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtIdAreaBuscar;
    private javax.swing.JTextField txtIdBuscar;
    // End of variables declaration//GEN-END:variables
}
