package VistaGestorEmpleados;

import GestionEmpleados.Empleado;
import GestionEmpleados.GestorEmpleados;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionEvent;
import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class EmpAsistencias extends javax.swing.JPanel {
    public static GestorEmpleados gestor = new GestorEmpleados();
    public static LocalDate fechaComoLocalDate;
    public static Date fechaSeleccionada;
    
    public EmpAsistencias(GestorEmpleados gestor) {
        this.gestor = gestor;
        initComponents();
        actualizarReloj();
        iniciarTimer();
        tablaAsistencias.setModel(new DefaultTableModel(new Object[][]{}, new String[]{"Tipo Hora", "Hora"}));
        txtNomAsis.setEditable(false);
        txtApeAsis.setEditable(false);
        txtDniAsis.setEditable(false);
        txtCorreoAsis.setEditable(false);
        reset();
    }

    private void actualizarReloj() {
        LocalTime ahora = LocalTime.now();
        lbReloj.setText(String.format("%02d : %02d : %02d", ahora.getHour(), ahora.getMinute(), ahora.getSecond()));
    }

    private void iniciarTimer() {
        new Timer(1000, (ActionEvent e) -> actualizarReloj()).start();
    }
    
    private void reset(){
            txtHoraEnt.setText("");
            txtMinEnt.setText("");
            txtHoraSal.setText("");
            txtMinSal.setText("");
            txtHoraEnt.setEditable(false);
            txtMinEnt.setEditable(false);
            txtHoraSal.setEditable(false);
            txtMinSal.setEditable(false);
    }
    
    private void compFecha(JDateChooser jd){
        if (jd.getDate() != null) {
            fechaSeleccionada = jd.getDate();
            fechaComoLocalDate = fechaSeleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            JOptionPane.showMessageDialog(this, "Trabajando con la fecha actual.");
            fechaComoLocalDate = LocalDate.now();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusqueda = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtIdEmpleadoAsist = new javax.swing.JScrollPane();
        tablaAsistencias = new javax.swing.JTable();
        jtBuscar = new javax.swing.JTabbedPane();
        panelIdBuscar = new javax.swing.JPanel();
        lblIDBuscar = new javax.swing.JLabel();
        jDateBuscar = new com.toedter.calendar.JDateChooser();
        lblBuscarOpc = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblEmpIdAsis = new javax.swing.JLabel();
        txtEmpIdAsis = new javax.swing.JTextField();
        lbNombre3 = new javax.swing.JLabel();
        txtNomAsis = new javax.swing.JTextField();
        lblApellido3 = new javax.swing.JLabel();
        txtApeAsis = new javax.swing.JTextField();
        lblDni3 = new javax.swing.JLabel();
        txtDniAsis = new javax.swing.JTextField();
        lblCorreo3 = new javax.swing.JLabel();
        txtCorreoAsis = new javax.swing.JTextField();
        btnMostrarAsis = new javax.swing.JButton();
        panelAreas = new javax.swing.JPanel();
        lblIdArea = new javax.swing.JLabel();
        jDHoras = new com.toedter.calendar.JDateChooser();
        panelAreas1 = new javax.swing.JPanel();
        lblIdArea1 = new javax.swing.JLabel();
        txtHoraEnt = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtMinEnt = new javax.swing.JTextField();
        btnAsistencias = new javax.swing.JButton();
        panelAreas4 = new javax.swing.JPanel();
        lblIdArea4 = new javax.swing.JLabel();
        txtHoraSal = new javax.swing.JTextField();
        lblArea3 = new javax.swing.JLabel();
        txtMinSal = new javax.swing.JTextField();
        panelReloj = new javax.swing.JPanel();
        lbReloj = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 50, 77));

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("PanelBusqueda"));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtIdEmpleadoAsist.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Empleados"));
        txtIdEmpleadoAsist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaAsistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txtIdEmpleadoAsist.setViewportView(tablaAsistencias);

        jtBuscar.setToolTipText("");

        lblIDBuscar.setText("Dia Registrado:");

        javax.swing.GroupLayout panelIdBuscarLayout = new javax.swing.GroupLayout(panelIdBuscar);
        panelIdBuscar.setLayout(panelIdBuscarLayout);
        panelIdBuscarLayout.setHorizontalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIDBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        panelIdBuscarLayout.setVerticalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIDBuscar)
            .addComponent(jDateBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jtBuscar.addTab("Día", panelIdBuscar);

        lblBuscarOpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc.setText("Buscar por(en blanco para todos):");

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdEmpleadoAsist)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBusquedaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBusquedaLayout.createSequentialGroup()
                                .addComponent(lblBuscarOpc, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblBuscarOpc)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdEmpleadoAsist, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empleado"));

        lblEmpIdAsis.setText("ID:");

        lbNombre3.setText("Nombre:");

        lblApellido3.setText("Apellido:");

        lblDni3.setText("DNI:");

        lblCorreo3.setText("Correo:");

        btnMostrarAsis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarAsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-del-portapapeles.png"))); // NOI18N
        btnMostrarAsis.setText("Mostrar Datos");
        btnMostrarAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAsisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblEmpIdAsis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtEmpIdAsis))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(lbNombre3)
                                .addGap(14, 14, 14)
                                .addComponent(txtNomAsis))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(lblApellido3)
                                .addGap(12, 12, 12)
                                .addComponent(txtApeAsis))))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDni3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblCorreo3)
                        .addGap(28, 28, 28)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreoAsis)
                            .addComponent(txtDniAsis)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addComponent(btnMostrarAsis, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpIdAsis)
                    .addComponent(txtEmpIdAsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMostrarAsis)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre3)
                    .addComponent(txtNomAsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido3)
                    .addComponent(txtApeAsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni3)
                    .addComponent(txtDniAsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo3)
                    .addComponent(txtCorreoAsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAreas.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar día"));

        lblIdArea.setText("Día: ");

        javax.swing.GroupLayout panelAreasLayout = new javax.swing.GroupLayout(panelAreas);
        panelAreas.setLayout(panelAreasLayout);
        panelAreasLayout.setHorizontalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelAreasLayout.setVerticalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArea)
                    .addComponent(jDHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelAreas1.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Hora: Entrada"));

        lblIdArea1.setText("Hora:");

        lblArea.setText("Minuto:");

        javax.swing.GroupLayout panelAreas1Layout = new javax.swing.GroupLayout(panelAreas1);
        panelAreas1.setLayout(panelAreas1Layout);
        panelAreas1Layout.setHorizontalGroup(
            panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArea1)
                    .addComponent(lblArea))
                .addGap(18, 18, 18)
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinEnt)
                    .addComponent(txtHoraEnt))
                .addContainerGap())
        );
        panelAreas1Layout.setVerticalGroup(
            panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArea1)
                    .addComponent(txtHoraEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtMinEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAsistencias.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N
        btnAsistencias.setText("Verificar Horas");
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });

        panelAreas4.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Hora:  Salida"));

        lblIdArea4.setText("Hora:");

        lblArea3.setText("Minuto: ");

        javax.swing.GroupLayout panelAreas4Layout = new javax.swing.GroupLayout(panelAreas4);
        panelAreas4.setLayout(panelAreas4Layout);
        panelAreas4Layout.setHorizontalGroup(
            panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArea4)
                    .addComponent(lblArea3))
                .addGap(18, 18, 18)
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinSal, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtHoraSal))
                .addContainerGap())
        );
        panelAreas4Layout.setVerticalGroup(
            panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArea4)
                    .addComponent(txtHoraSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea3)
                    .addComponent(txtMinSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbReloj.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbReloj.setForeground(new java.awt.Color(255, 0, 51));
        lbReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReloj.setText("00 : 00 : 00");

        javax.swing.GroupLayout panelRelojLayout = new javax.swing.GroupLayout(panelReloj);
        panelReloj.setLayout(panelRelojLayout);
        panelRelojLayout.setHorizontalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelojLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRelojLayout.setVerticalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelojLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReloj, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelAreas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAreas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(panelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelAreas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(panelAreas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelReloj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        if (btnAsistencias.getText().equals("Verificar Horas")) {
            if (txtEmpIdAsis.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el ID de empleado.");
                return;
            }
            try {
                int id = Integer.parseInt(txtEmpIdAsis.getText());
                if (gestor.getEmpleado(id) != null) {
                    compFecha(jDHoras);
                    List<Integer> horasList = gestor.getEmpleado(id).getHorasTrabajadasPorDia()
                        .getOrDefault(fechaComoLocalDate, new ArrayList<>());
                    boolean esPar = horasList.size() % 2 == 0;
                    txtHoraEnt.setEditable(esPar);
                    txtMinEnt.setEditable(esPar);
                    txtHoraSal.setEditable(!esPar);
                    txtMinSal.setEditable(!esPar);
                    btnAsistencias.setText("Registrar Hora");
                    txtEmpIdAsis.setEditable(false);
                    jDHoras.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Error... No existe el empleado.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error... Número inválido.");
            }
        } else {
            if (txtHoraEnt.getText().isEmpty() && txtMinEnt.getText().isEmpty()
                && txtHoraSal.getText().isEmpty() && txtMinSal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Error... Ingrese una hora completa.");
                return;
            }
            try {
                int id = Integer.parseInt(txtEmpIdAsis.getText());
                List<Integer> original = gestor.getEmpleado(id).getHorasTrabajadasPorDia()
                    .getOrDefault(fechaComoLocalDate, new ArrayList<>());
                List<Integer> lista = new ArrayList<>(original);
                int horasSum = (txtHoraEnt.getText().isEmpty()?0:Integer.parseInt(txtHoraEnt.getText()))
                             + (txtHoraSal.getText().isEmpty()?0:Integer.parseInt(txtHoraSal.getText()));
                int minSum = (txtMinEnt.getText().isEmpty()?0:Integer.parseInt(txtMinEnt.getText()))
                           + (txtMinSal.getText().isEmpty()?0:Integer.parseInt(txtMinSal.getText()));
                if (horasSum < 0 || horasSum > 24 || minSum < 0 || minSum > 60) {
                    JOptionPane.showMessageDialog(this, "Error... Hora o minutos inválidos.");
                    return;
                }
                if (minSum >= 30) horasSum++;
                if (!original.isEmpty() && horasSum <= original.get(original.size()-1)) {
                    JOptionPane.showMessageDialog(this, "Error... Hora incoherente con el registro.");
                    return;
                }
                lista.add(horasSum);
                gestor.getEmpleado(id).registrarHorasDiarias(fechaComoLocalDate, lista);
                gestor.getEmpleado(id).registrarAsistencia(fechaComoLocalDate, true);
                btnAsistencias.setText("Verificar Horas");
                txtEmpIdAsis.setEditable(true);
                jDHoras.setEnabled(true);
                reset();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error... Formato inválido.");
            }
        }
        btnAsistencias.setSize(213, 75);
    }//GEN-LAST:event_btnAsistenciasActionPerformed

    private void btnMostrarAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAsisActionPerformed
        try {
            int id = Integer.parseInt(txtEmpIdAsis.getText());
            Empleado emp = gestor.getEmpleado(id);
            if (emp != null) {
                txtEmpIdAsis.setText(String.valueOf(emp.getId()));
                txtNomAsis.setText(emp.getNombre());
                txtApeAsis.setText(emp.getApellido());
                txtDniAsis.setText(emp.getDni());
                txtCorreoAsis.setText(emp.getEmail());
            } else {
                JOptionPane.showMessageDialog(this, "Error... No existe el empleado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error... Número inválido.");
        }
    }//GEN-LAST:event_btnMostrarAsisActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtEmpIdAsis.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de empleado.");
            return;
        }
        compFecha(jDateBuscar);
        try {
            int id = Integer.parseInt(txtEmpIdAsis.getText());
            if (gestor.getEmpleado(id) != null) {
                List<Integer> horas = gestor.getEmpleado(id).getHorasTrabajadasPorDia()
                    .getOrDefault(fechaComoLocalDate, new ArrayList<>());
                DefaultTableModel modelo = (DefaultTableModel) tablaAsistencias.getModel();
                modelo.setRowCount(0);
                for (int i = 0; i < horas.size(); i++) {
                    modelo.addRow(new Object[]{(i % 2 == 0)?"Entrada":"Salida", horas.get(i)});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error... No existe el empleado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error... Número inválido.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarAsis;
    private com.toedter.calendar.JDateChooser jDHoras;
    private com.toedter.calendar.JDateChooser jDateBuscar;
    private javax.swing.JTabbedPane jtBuscar;
    private javax.swing.JLabel lbNombre3;
    private javax.swing.JLabel lbReloj;
    private javax.swing.JLabel lblApellido3;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea3;
    private javax.swing.JLabel lblBuscarOpc;
    private javax.swing.JLabel lblCorreo3;
    private javax.swing.JLabel lblDni3;
    private javax.swing.JLabel lblEmpIdAsis;
    private javax.swing.JLabel lblIDBuscar;
    private javax.swing.JLabel lblIdArea;
    private javax.swing.JLabel lblIdArea1;
    private javax.swing.JLabel lblIdArea4;
    private javax.swing.JPanel panelAreas;
    private javax.swing.JPanel panelAreas1;
    private javax.swing.JPanel panelAreas4;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelIdBuscar;
    private javax.swing.JPanel panelReloj;
    private javax.swing.JTable tablaAsistencias;
    private javax.swing.JTextField txtApeAsis;
    private javax.swing.JTextField txtCorreoAsis;
    private javax.swing.JTextField txtDniAsis;
    private javax.swing.JTextField txtEmpIdAsis;
    private javax.swing.JTextField txtHoraEnt;
    private javax.swing.JTextField txtHoraSal;
    private javax.swing.JScrollPane txtIdEmpleadoAsist;
    private javax.swing.JTextField txtMinEnt;
    private javax.swing.JTextField txtMinSal;
    private javax.swing.JTextField txtNomAsis;
    // End of variables declaration//GEN-END:variables
}
