/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaGestorEmpleados;

import GestionEmpleados.GestorEmpleados;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class EmpAsistencias extends javax.swing.JPanel {

    
    
    public static GestorEmpleados gestor = new GestorEmpleados();
    /**
     * Creates new form GestionAreasPanel
     * @param gestor
     */
    public EmpAsistencias(GestorEmpleados gestor) {
        initComponents();
        this.gestor = gestor;
        
        LocalTime a = LocalTime.now();
        lbReloj.setText(
                String.format("%02d : %02d : %02d",
                a.getHour(),
                a.getMinute(),
                a.getSecond()));
        
        
        gestor.getEmpleado(101).registrarHorasDiarias(LocalDate.now(), Arrays.asList(1,5,6,7,9));
        gestor.getEmpleado(102).registrarHorasDiarias(LocalDate.now(), Arrays.asList(1,8));
        
        int timer = 1000;
        

        
        new Timer(timer, (ActionEvent e) -> {
                LocalTime ahora = LocalTime.now();
                lbReloj.setText(
                String.format("%02d : %02d : %02d",
                ahora.getHour(),
                ahora.getMinute(),
                ahora.getSecond())
                );
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusqueda = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtIdEmpleadoAsist = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jtBuscar = new javax.swing.JTabbedPane();
        panelIdBuscar = new javax.swing.JPanel();
        lblIDBuscar = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        lblBuscarOpc = new javax.swing.JLabel();
        panelSoloEmpl3 = new javax.swing.JPanel();
        lbID3 = new javax.swing.JLabel();
        txtIdEmpleadoAs = new javax.swing.JTextField();
        lbNombre3 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JTextField();
        lblApellido3 = new javax.swing.JLabel();
        txtApellido3 = new javax.swing.JTextField();
        lblDni3 = new javax.swing.JLabel();
        txtDNI3 = new javax.swing.JTextField();
        lblCorreo3 = new javax.swing.JLabel();
        txtCorreo3 = new javax.swing.JTextField();
        btnModifiar3 = new javax.swing.JButton();
        panelAreas = new javax.swing.JPanel();
        lblIdArea = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        panelAreas1 = new javax.swing.JPanel();
        lblIdArea1 = new javax.swing.JLabel();
        txtHoraEnt = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtMinEnt = new javax.swing.JTextField();
        btnAsistencias = new javax.swing.JButton();
        panelAreas4 = new javax.swing.JPanel();
        lblIdArea4 = new javax.swing.JLabel();
        txtHoraSal = new javax.swing.JTextField();
        lblArea3 = new javax.swing.JLabel();
        txtMinSal = new javax.swing.JTextField();
        panelReloj = new javax.swing.JPanel();
        lbReloj = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 50, 77));

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("PanelBusqueda"));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        txtIdEmpleadoAsist.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Empleados"));
        txtIdEmpleadoAsist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txtIdEmpleadoAsist.setViewportView(tbLista);

        jtBuscar.setToolTipText("");

        lblIDBuscar.setText("Dia Registrado:");

        javax.swing.GroupLayout panelIdBuscarLayout = new javax.swing.GroupLayout(panelIdBuscar);
        panelIdBuscar.setLayout(panelIdBuscarLayout);
        panelIdBuscarLayout.setHorizontalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblIDBuscar)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(171, 171, 171))
        );
        panelIdBuscarLayout.setVerticalGroup(
            panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblIDBuscar))
        );

        jtBuscar.addTab("Día", panelIdBuscar);

        lblBuscarOpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarOpc.setText("Buscar por(en blanco para todos):");

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdEmpleadoAsist)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBusquedaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBusquedaLayout.createSequentialGroup()
                                .addComponent(lblBuscarOpc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblBuscarOpc)
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdEmpleadoAsist, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSoloEmpl3.setBackground(new java.awt.Color(255, 255, 255));
        panelSoloEmpl3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empleado"));

        lbID3.setText("ID:");

        lbNombre3.setText("Nombre:");

        lblApellido3.setText("Apellido:");

        lblDni3.setText("DNI:");

        lblCorreo3.setText("Correo:");

        btnModifiar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModifiar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista-del-portapapeles.png"))); // NOI18N
        btnModifiar3.setText("Mostrar Datos");

        javax.swing.GroupLayout panelSoloEmpl3Layout = new javax.swing.GroupLayout(panelSoloEmpl3);
        panelSoloEmpl3.setLayout(panelSoloEmpl3Layout);
        panelSoloEmpl3Layout.setHorizontalGroup(
            panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbID3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtIdEmpleadoAs))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSoloEmpl3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                                .addComponent(lbNombre3)
                                .addGap(14, 14, 14)
                                .addComponent(txtNombre3))
                            .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                                .addComponent(lblApellido3)
                                .addGap(12, 12, 12)
                                .addComponent(txtApellido3))))
                    .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDni3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                        .addComponent(lblCorreo3)
                        .addGap(28, 28, 28)
                        .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo3)
                            .addComponent(txtDNI3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSoloEmpl3Layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addComponent(btnModifiar3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelSoloEmpl3Layout.setVerticalGroup(
            panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoloEmpl3Layout.createSequentialGroup()
                .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID3)
                    .addComponent(txtIdEmpleadoAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModifiar3)
                .addGap(18, 18, 18)
                .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre3)
                    .addComponent(txtNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido3)
                    .addComponent(txtApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni3)
                    .addComponent(txtDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSoloEmpl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo3)
                    .addComponent(txtCorreo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAreas.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar día"));

        lblIdArea.setText("Día: ");

        javax.swing.GroupLayout panelAreasLayout = new javax.swing.GroupLayout(panelAreas);
        panelAreas.setLayout(panelAreasLayout);
        panelAreasLayout.setHorizontalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDia)
                .addContainerGap())
        );
        panelAreasLayout.setVerticalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdArea))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAreas1.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Hora: Entrada"));

        lblIdArea1.setText("Hora:");

        lblArea.setText("Minuto:");

        javax.swing.GroupLayout panelAreas1Layout = new javax.swing.GroupLayout(panelAreas1);
        panelAreas1.setLayout(panelAreas1Layout);
        panelAreas1Layout.setHorizontalGroup(
            panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArea1)
                    .addComponent(lblArea))
                .addGap(18, 18, 18)
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinEnt)
                    .addComponent(txtHoraEnt))
                .addContainerGap())
        );
        panelAreas1Layout.setVerticalGroup(
            panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArea1)
                    .addComponent(txtHoraEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAreas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtMinEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAsistencias.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N
        btnAsistencias.setText("Verificar Horas");
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });

        panelAreas4.setBackground(new java.awt.Color(255, 255, 255));
        panelAreas4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Hora:  Salida"));

        lblIdArea4.setText("Hora:");

        lblArea3.setText("Minuto: ");

        javax.swing.GroupLayout panelAreas4Layout = new javax.swing.GroupLayout(panelAreas4);
        panelAreas4.setLayout(panelAreas4Layout);
        panelAreas4Layout.setHorizontalGroup(
            panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArea4)
                    .addComponent(lblArea3))
                .addGap(18, 18, 18)
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinSal, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtHoraSal))
                .addContainerGap())
        );
        panelAreas4Layout.setVerticalGroup(
            panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreas4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArea4)
                    .addComponent(txtHoraSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAreas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea3)
                    .addComponent(txtMinSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbReloj.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbReloj.setForeground(new java.awt.Color(255, 0, 51));
        lbReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReloj.setText("00 : 00 : 00");

        javax.swing.GroupLayout panelRelojLayout = new javax.swing.GroupLayout(panelReloj);
        panelReloj.setLayout(panelRelojLayout);
        panelRelojLayout.setHorizontalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelojLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRelojLayout.setVerticalGroup(
            panelRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelojLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReloj, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSoloEmpl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelAreas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAreas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(panelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelAreas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(panelAreas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelSoloEmpl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelReloj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        if (btnAsistencias.getText().equals("Verificar Horas")){
            int id = Integer.parseInt(txtIdEmpleadoAs.getText());
            int horasTrabajadas = gestor.getEmpleado(id).getHorasTrabajadasPorDia().get(LocalDate.now()).size();
            
            if ((horasTrabajadas) % 2 == 0){
                //Si el empleado tiene una cantidad de horas registradas pares, marca entrada
                txtHoraEnt.setEditable(true);
                txtMinEnt.setEditable(true);
                txtHoraSal.setEditable(false);
                txtMinSal.setEditable(false);
            }else {
                //Si el empleado tiene una cantidad de horas registradas impares, marca salida
                txtHoraEnt.setEditable(false);
                txtMinEnt.setEditable(false);
                txtHoraSal.setEditable(true);
                txtMinSal.setEditable(true);
            }
        }
        
        
        btnAsistencias.setSize(213, 75);
    }//GEN-LAST:event_btnAsistenciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModifiar;
    private javax.swing.JButton btnModifiar1;
    private javax.swing.JButton btnModifiar2;
    private javax.swing.JButton btnModifiar3;
    private javax.swing.JTabbedPane jtBuscar;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbID1;
    private javax.swing.JLabel lbID2;
    private javax.swing.JLabel lbID3;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbNombre2;
    private javax.swing.JLabel lbNombre3;
    private javax.swing.JLabel lbReloj;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblApellido3;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblArea2;
    private javax.swing.JLabel lblArea3;
    private javax.swing.JLabel lblBuscarOpc;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCorreo2;
    private javax.swing.JLabel lblCorreo3;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblDni2;
    private javax.swing.JLabel lblDni3;
    private javax.swing.JLabel lblIDBuscar;
    private javax.swing.JLabel lblIdArea;
    private javax.swing.JLabel lblIdArea1;
    private javax.swing.JLabel lblIdArea2;
    private javax.swing.JLabel lblIdArea3;
    private javax.swing.JLabel lblIdArea4;
    private javax.swing.JPanel panelAreas;
    private javax.swing.JPanel panelAreas1;
    private javax.swing.JPanel panelAreas2;
    private javax.swing.JPanel panelAreas3;
    private javax.swing.JPanel panelAreas4;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelIdBuscar;
    private javax.swing.JPanel panelReloj;
    private javax.swing.JPanel panelSoloEmpl;
    private javax.swing.JPanel panelSoloEmpl1;
    private javax.swing.JPanel panelSoloEmpl2;
    private javax.swing.JPanel panelSoloEmpl3;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtApellido3;
    private javax.swing.JTextField txtArea1;
    private javax.swing.JTextField txtArea2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtCorreo3;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNI1;
    private javax.swing.JTextField txtDNI2;
    private javax.swing.JTextField txtDNI3;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtHoraEnt;
    private javax.swing.JTextField txtHoraSal;
    private javax.swing.JTextField txtIdArea2;
    private javax.swing.JTextField txtIdArea3;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdEmpleado1;
    private javax.swing.JTextField txtIdEmpleado2;
    private javax.swing.JTextField txtIdEmpleadoAs;
    private javax.swing.JScrollPane txtIdEmpleadoAsist;
    private javax.swing.JTextField txtMinEnt;
    private javax.swing.JTextField txtMinSal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNombre3;
    // End of variables declaration//GEN-END:variables
}
